export const addCategoryModalText = {
  en: {
    title: "Add New Category",
    cancel: "Cancel",
    confirm: "Confirm",
    adding: "Adding...",
    labelEnglish: "English",
    labelFrench: "Français",
    labelArabic: "Arabic",
    placeholderName: "name",
    missingTranslationsTitle: "Missing Translations",
    missingTranslationsMessage: "Please fill in:",
    toastSuccessTitle: "Category Added",
    toastSuccessMessage: "New category has been added successfully.",
    toastErrorTitle: "Save Failed",
    missingEnglish: "English",
    missingFrench: "French",
    missingArabic: "Arabic",
  },
  fr: {
    title: "Ajouter une nouvelle catégorie",
    cancel: "Annuler",
    confirm: "Confirmer",
    adding: "Ajout en cours...",
    labelEnglish: "Anglais",
    labelFrench: "Français",
    labelArabic: "Arabe",
    placeholderName: "nom",
    missingTranslationsTitle: "Traductions manquantes",
    missingTranslationsMessage: "Veuillez remplir :",
    toastSuccessTitle: "Catégorie ajoutée",
    toastSuccessMessage: "La nouvelle catégorie a été ajoutée avec succès.",
    toastErrorTitle: "Échec de l'enregistrement",
    missingEnglish: "Anglais",
    missingFrench: "Français",
    missingArabic: "Arabe",
  },
} as const;