export const addDishModalText = {
  en: {
    title: "Add New Dish",
    cancel: "Cancel",
    confirm: "Confirm",
    adding: "Adding...",
    labelEnglish: "English",
    labelFrench: "Français",
    labelArabic: "العربية",
    placeholderEnglish: "Dish name",
    placeholderFrench: "Nom du plat",
    placeholderArabic: "اسم الطبق",
    descriptionLabel: "Description",
    descriptionOptional: "(optional)",
    descriptionPlaceholderEn: "Add a description for this dish (optional)",
    descriptionPlaceholderFr: "Ajoutez une description pour ce plat (facultatif)",
    descriptionPlaceholderAr: "أضف وصفًا لهذا الطبق (اختياري)",
    sizesLabel: "Sizes",
    addSizeLabel: "Add size",
    sizeNamePlaceholder: "e.g. Small, Large",
    categoryLabel: "Category",
    categoryPlaceholder: "Select a category",
    availabilityLabel: "Availability",
    availableOption: "Available",
    unavailableOption: "Unavailable",
    visibilityLabel: "Visibility",
    visibleOption: "Visible",
    hiddenOption: "Hidden",
    errorEnglishRequired: "English name is required.",
    errorFrenchRequired: "French name is required.",
    errorArabicRequired: "Arabic name is required.",
    errorSizesRequired: "Add at least one size with a name and a price greater than 0.",
    errorCategoryRequired: "Please select a category.",
    toastSuccessTitle: "Dish Added",
    toastSuccessMessage: "New dish has been added successfully.",
    toastErrorTitle: "Save Failed",
    errorPriceRequired: "Please enter a price.",
    singleSizeHint: "Add another size if this dish has multiple options (e.g. Small / Large).",
  },
  fr: {
    title: "Ajouter un nouveau plat",
    cancel: "Annuler",
    confirm: "Confirmer",
    adding: "Ajout en cours...",
    labelEnglish: "Anglais",
    labelFrench: "Français",
    labelArabic: "العربية",
    placeholderEnglish: "Dish name",
    placeholderFrench: "Nom du plat",
    placeholderArabic: "اسم الطبق",
    descriptionLabel: "Description",
    descriptionOptional: "(facultatif)",
    descriptionPlaceholderEn: "Add a description for this dish (optional)",
    descriptionPlaceholderFr: "Ajoutez une description pour ce plat (facultatif)",
    descriptionPlaceholderAr: "أضف وصفًا لهذا الطبق (اختياري)",
    sizesLabel: "Tailles",
    addSizeLabel: "Ajouter une taille",
sizeNamePlaceholder: "ex. Petit, Grand",
    categoryLabel: "Catégorie",
    categoryPlaceholder: "Sélectionner une catégorie",
    availabilityLabel: "Disponibilité",
    availableOption: "Disponible",
    unavailableOption: "Indisponible",
    visibilityLabel: "Visibilité",
    visibleOption: "Visible",
    hiddenOption: "Masqué",
    errorEnglishRequired: "Le nom en anglais est requis.",
    errorFrenchRequired: "Le nom en français est requis.",
    errorArabicRequired: "Le nom en arabe est requis.",
    errorSizesRequired: "Ajoutez au moins une taille avec un nom et un prix supérieur à 0.",
    errorCategoryRequired: "Veuillez sélectionner une catégorie.",
    toastSuccessTitle: "Plat ajouté",
    toastSuccessMessage: "Le nouveau plat a été ajouté avec succès.",
    toastErrorTitle: "Échec de l'enregistrement",
    errorPriceRequired: "Veuillez saisir un prix.",
    singleSizeHint: "Ajoutez une autre taille si ce plat a plusieurs options (ex. Petit / Grand).",
  },
} as const;