export const addDishModalText = {
  en: {
    title: "Add New Dish",
    cancel: "Cancel",
    confirm: "Confirm",
    adding: "Adding...",
    labelEnglish: "English",
    labelFrench: "Français",
    labelArabic: "العربية",
    placeholderEnglish: "Dish name",
    placeholderFrench: "Nom du plat",
    placeholderArabic: "اسم الطبق",
    descriptionLabel: "Description",
    descriptionOptional: "(optional)",
    descriptionPlaceholderEn: "Add a description for this dish (optional)",
    descriptionPlaceholderFr: "Ajoutez une description pour ce plat (facultatif)",
    descriptionPlaceholderAr: "أضف وصفًا لهذا الطبق (اختياري)",
    priceLabel: "Price",
    categoryLabel: "Category",
    categoryPlaceholder: "Select a category",
    availabilityLabel: "Availability",
    availableOption: "Available",
    unavailableOption: "Unavailable",
    visibilityLabel: "Visibility",
    visibleOption: "Visible",
    hiddenOption: "Hidden",
    errorEnglishRequired: "English name is required.",
    errorFrenchRequired: "French name is required.",
    errorArabicRequired: "Arabic name is required.",
    errorPriceRequired: "Price must be greater than 0.",
    errorCategoryRequired: "Please select a category.",
    toastSuccessTitle: "Dish Added",
    toastSuccessMessage: "New dish has been added successfully.",
    toastErrorTitle: "Save Failed",
  },
  fr: {
    title: "Ajouter un nouveau plat",
    cancel: "Annuler",
    confirm: "Confirmer",
    adding: "Ajout en cours...",
    labelEnglish: "Anglais",
    labelFrench: "Français",
    labelArabic: "العربية",
    placeholderEnglish: "Dish name",
    placeholderFrench: "Nom du plat",
    placeholderArabic: "اسم الطبق",
    descriptionLabel: "Description",
    descriptionOptional: "(facultatif)",
    descriptionPlaceholderEn: "Add a description for this dish (optional)",
    descriptionPlaceholderFr: "Ajoutez une description pour ce plat (facultatif)",
    descriptionPlaceholderAr: "أضف وصفًا لهذا الطبق (اختياري)",
    priceLabel: "Prix",
    categoryLabel: "Catégorie",
    categoryPlaceholder: "Sélectionner une catégorie",
    availabilityLabel: "Disponibilité",
    availableOption: "Disponible",
    unavailableOption: "Indisponible",
    visibilityLabel: "Visibilité",
    visibleOption: "Visible",
    hiddenOption: "Masqué",
    errorEnglishRequired: "Le nom en anglais est requis.",
    errorFrenchRequired: "Le nom en français est requis.",
    errorArabicRequired: "Le nom en arabe est requis.",
    errorPriceRequired: "Le prix doit être supérieur à 0.",
    errorCategoryRequired: "Veuillez sélectionner une catégorie.",
    toastSuccessTitle: "Plat ajouté",
    toastSuccessMessage: "Le nouveau plat a été ajouté avec succès.",
    toastErrorTitle: "Échec de l'enregistrement",
  },
} as const;