export const addSupplementModalText = {
  en: {
    title: "Add New Supplement",
    cancel: "Cancel",
    confirm: "Confirm",
    adding: "Adding...",
    labelEnglish: "English",
    labelFrench: "Français",
    labelArabic: "العربية",
    placeholderEnglish: "Supplement name",
    placeholderFrench: "Nom du supplément",
    placeholderArabic: "اسم الإضافة",
    priceLabel: "Price",
    availabilityLabel: "Availability",
    availableOption: "Available",
    unavailableOption: "Unavailable",
    visibilityLabel: "Visibility",
    visibleOption: "Visible",
    hiddenOption: "Hidden",
    errorEnglishRequired: "English name is required.",
    errorFrenchRequired: "French name is required.",
    errorArabicRequired: "Arabic name is required.",
    errorPriceRequired: "Price must be greater than 0.",
    toastSuccessTitle: "Supplement Added",
    toastSuccessMessage: "New supplement has been added successfully.",
  },
  fr: {
    title: "Ajouter un nouveau supplément",
    cancel: "Annuler",
    confirm: "Confirmer",
    adding: "Ajout en cours...",
    labelEnglish: "Anglais",
    labelFrench: "Français",
    labelArabic: "العربية",
    placeholderEnglish: "Supplement name",
    placeholderFrench: "Nom du supplément",
    placeholderArabic: "اسم الإضافة",
    priceLabel: "Prix",
    availabilityLabel: "Disponibilité",
    availableOption: "Disponible",
    unavailableOption: "Indisponible",
    visibilityLabel: "Visibilité",
    visibleOption: "Visible",
    hiddenOption: "Masqué",
    errorEnglishRequired: "Le nom en anglais est requis.",
    errorFrenchRequired: "Le nom en français est requis.",
    errorArabicRequired: "Le nom en arabe est requis.",
    errorPriceRequired: "Le prix doit être supérieur à 0.",
    toastSuccessTitle: "Supplément ajouté",
    toastSuccessMessage: "Le nouveau supplément a été ajouté avec succès.",
  },
} as const;