export const changePasswordText = {
  en: {
    sectionTitle: "Password",
    sectionDescription: "Manage your account password",
    passwordLabel: "Password",
    passwordMask: "••••••••••••",
    changePasswordBtn: "Change Password",
    changePasswordTitle: "Change Password",
    currentPasswordLabel: "Current Password",
    currentPasswordPlaceholder: "Enter current password",
    newPasswordLabel: "New Password",
    newPasswordPlaceholder: "Min 6 characters",
    confirmPasswordLabel: "Confirm Password",
    confirmPasswordPlaceholder: "Repeat new password",
    cancel: "Cancel",
    save: "Update Password",
    saving: "Saving...",
    errorCurrentRequired: "Current password is required.",
    errorNewRequired: "New password is required.",
    errorNewMinLength: "Password must be at least 6 characters.",
    errorConfirmRequired: "Please confirm your new password.",
    errorConfirmMatch: "Passwords do not match.",
    toastSuccessTitle: "Password Updated",
    toastSuccessMessage: "Your password has been changed.",
    toastErrorTitle: "Update Failed",
  },
  fr: {
    sectionTitle: "Mot de passe",
    sectionDescription: "Gérez le mot de passe de votre compte",
    passwordLabel: "Mot de passe",
    passwordMask: "••••••••••••",
    changePasswordBtn: "Changer le mot de passe",
    changePasswordTitle: "Changer le mot de passe",
    currentPasswordLabel: "Mot de passe actuel",
    currentPasswordPlaceholder: "Entrez le mot de passe actuel",
    newPasswordLabel: "Nouveau mot de passe",
    newPasswordPlaceholder: "Min 6 caractères",
    confirmPasswordLabel: "Confirmer le mot de passe",
    confirmPasswordPlaceholder: "Répétez le nouveau mot de passe",
    cancel: "Annuler",
    save: "Mettre à jour",
    saving: "Enregistrement...",
    errorCurrentRequired: "Le mot de passe actuel est requis.",
    errorNewRequired: "Le nouveau mot de passe est requis.",
    errorNewMinLength: "Le mot de passe doit contenir au moins 6 caractères.",
    errorConfirmRequired: "Veuillez confirmer votre nouveau mot de passe.",
    errorConfirmMatch: "Les mots de passe ne correspondent pas.",
    toastSuccessTitle: "Mot de passe mis à jour",
    toastSuccessMessage: "Votre mot de passe a été modifié.",
    toastErrorTitle: "Échec de la mise à jour",
  },
} as const;