export const dishRowText = {
  en: {
    missing: "Missing",
    cancel: "Cancel",
    save: "Save",
    errorEnglishRequired: "English name is required.",
    errorFrenchRequired: "French name is required.",
    errorArabicRequired: "Arabic name is required.",
    toastDeletedTitle: "Dish Deleted",
    toastDeletedMessage: "Dish has been deleted successfully.",
    toastDeleteFailedTitle: "Delete Failed",
    toastUpdatedTitle: "Dish Updated",
    toastUpdatedMessage: "Dish has been updated successfully.",
    toastSaveFailedTitle: "Save Failed",
    toastUpdateFailedTitle: "Update Failed",
  },
  fr: {
    missing: "Manquant",
    cancel: "Annuler",
    save: "Enregistrer",
    errorEnglishRequired: "Le nom en anglais est requis.",
    errorFrenchRequired: "Le nom en français est requis.",
    errorArabicRequired: "Le nom en arabe est requis.",
    toastDeletedTitle: "Plat supprimé",
    toastDeletedMessage: "Le plat a été supprimé avec succès.",
    toastDeleteFailedTitle: "Échec de la suppression",
    toastUpdatedTitle: "Plat mis à jour",
    toastUpdatedMessage: "Le plat a été mis à jour avec succès.",
    toastSaveFailedTitle: "Échec de l'enregistrement",
    toastUpdateFailedTitle: "Échec de la mise à jour",
  },
} as const;