export const supplementRowText = {
  en: {
    missing: "Missing",
    cancel: "Cancel",
    save: "Save",
    errorEnglishRequired: "English name is required.",
    errorFrenchRequired: "French name is required.",
    errorArabicRequired: "Arabic name is required.",
    errorPriceRequired: "Price must be greater than 0.",
    toastDeletedTitle: "Supplement Deleted",
    toastDeletedMessage: "Supplement has been deleted successfully.",
    toastDeleteFailedTitle: "Delete Failed",
    toastUpdatedTitle: "Supplement Updated",
    toastUpdatedMessage: "Supplement has been updated successfully.",
    toastSaveFailedTitle: "Save Failed",
    toastUpdateFailedTitle: "Update Failed",
  },
  fr: {
    missing: "Manquant",
    cancel: "Annuler",
    save: "Enregistrer",
    errorEnglishRequired: "Le nom en anglais est requis.",
    errorFrenchRequired: "Le nom en français est requis.",
    errorArabicRequired: "Le nom en arabe est requis.",
    errorPriceRequired: "Le prix doit être supérieur à 0.",
    toastDeletedTitle: "Supplément supprimé",
    toastDeletedMessage: "Le supplément a été supprimé avec succès.",
    toastDeleteFailedTitle: "Échec de la suppression",
    toastUpdatedTitle: "Supplément mis à jour",
    toastUpdatedMessage: "Le supplément a été mis à jour avec succès.",
    toastSaveFailedTitle: "Échec de l'enregistrement",
    toastUpdateFailedTitle: "Échec de la mise à jour",
  },
} as const;