export const bannersText = {
  en: {
    pageTitle: "Banners",
    manageTitle: "Manage Banners",
    manageDescription: "Upload up to 3 banner images for your menu carousel",
    limitReachedTitle: "Banner Limit Reached",
    limitReachedMessage:
      "You have reached the maximum of 3 banners. Remove an existing banner to upload a new one.",
    tapToSelect: "Tap to select a banner",
    bannerPreviewAlt: "Banner preview",
    cancel: "Cancel",
    confirm: "Confirm",
    uploading: "Uploading...",
    currentBannersTitle: "Current Banners",
    currentBannersDescription: "Hover on the image to edit",
    noBannersTitle: "No Banners Yet",
    noBannersMessage:
      "Upload your first banner to display promotional content in your menu carousel.",
    loading: "Loading banners...",
    loadError: "Could not load banners.",
    toastAddedTitle: "Banner Added",
    toastAddedMessage: "Your banner has been uploaded.",
    toastAddFailedTitle: "Upload Failed",
    toastDeletedTitle: "Banner Deleted",
    toastDeletedMessage: "Banner has been removed.",
    toastDeleteFailedTitle: "Delete Failed",
    toastUpdateFailedTitle: "Update Failed",
  },
  fr: {
    pageTitle: "Bannières",
    manageTitle: "Gérer les bannières",
    manageDescription:
      "Téléversez jusqu'à 3 images de bannière pour votre carrousel de menu",
    limitReachedTitle: "Limite de bannières atteinte",
    limitReachedMessage:
      "Vous avez atteint le maximum de 3 bannières. Supprimez une bannière existante pour en téléverser une nouvelle.",
    tapToSelect: "Touchez pour sélectionner une bannière",
    bannerPreviewAlt: "Aperçu de la bannière",
    cancel: "Annuler",
    confirm: "Confirmer",
    uploading: "Téléversement...",
    currentBannersTitle: "Bannières actuelles",
    currentBannersDescription: "Survolez l'image pour la modifier",
    noBannersTitle: "Aucune bannière",
    noBannersMessage:
      "Téléversez votre première bannière pour afficher du contenu promotionnel dans votre carrousel de menu.",
    loading: "Chargement des bannières...",
    loadError: "Impossible de charger les bannières.",
    toastAddedTitle: "Bannière ajoutée",
    toastAddedMessage: "Votre bannière a été téléversée.",
    toastAddFailedTitle: "Échec du téléversement",
    toastDeletedTitle: "Bannière supprimée",
    toastDeletedMessage: "La bannière a été supprimée.",
    toastDeleteFailedTitle: "Échec de la suppression",
    toastUpdateFailedTitle: "Échec de la mise à jour",
  },
} as const;