export const categoriesText = {
  en: {
    pageTitle: "Category Manager",
    pageDescription: "Organize and manage your menu categories",
    addCategory: "Add Category",
    loading: "Loading categories...",
    loadError: "Could not load categories.",
    noMenuError: "No menu found for this restaurant. Please create a menu first.",
    missingTranslationsTitle: "Missing Translations",
    missingTranslationsSingle: "category has missing translations. Edit them to add all required languages.",
    missingTranslationsPlural: "categories have missing translations. Edit them to add all required languages.",
    colOrder: "Order",
    colIcon: "Icon",
    colEnglish: "English",
    colFrench: "Français",
    colArabic: "Arabic",
    colStatus: "Status",
    colActions: "Actions",
  },
  fr: {
    pageTitle: "Gestionnaire de catégories",
    pageDescription: "Organisez et gérez les catégories de votre menu",
    addCategory: "Ajouter une catégorie",
    loading: "Chargement des catégories...",
    loadError: "Impossible de charger les catégories.",
    noMenuError: "Aucun menu trouvé pour ce restaurant. Veuillez d'abord créer un menu.",
    missingTranslationsTitle: "Traductions manquantes",
    missingTranslationsSingle: "catégorie a des traductions manquantes. Modifiez-les pour ajouter toutes les langues requises.",
    missingTranslationsPlural: "catégories ont des traductions manquantes. Modifiez-les pour ajouter toutes les langues requises.",
    colOrder: "Ordre",
    colIcon: "Icône",
    colEnglish: "Anglais",
    colFrench: "Français",
    colArabic: "Arabe",
    colStatus: "Statut",
    colActions: "Actions",
  },
} as const;