export const dishesText = {
  en: {
    pageTitle: "Dish Manager",
    pageDescription: "Organize and manage your menu dishes",
    addDish: "Add Dish",
    loading: "Loading dishes...",
    loadError: "Could not load dishes.",
    noRestaurantError: "No restaurant found. Please log in again.",
    missingTranslationsTitle: "Missing Translations",
    missingTranslationsSingle:
      "dish has missing translations. Edit them to add all required languages.",
    missingTranslationsPlural:
      "dishes have missing translations. Edit them to add all required languages.",
    colOrder: "Order",
    colIcon: "Icon",
    colEnglish: "English",
    colFrench: "Français",
    colArabic: "Arabic",
    colDescription: "Description",
    colSizes: "Sizes",
    colAvailable: "Available",
    colStatus: "Status",
    colLikes: "Likes",
    colActions: "Actions",
  },
  fr: {
    pageTitle: "Gestionnaire de plats",
    pageDescription: "Organisez et gérez les plats de votre menu",
    addDish: "Ajouter un plat",
    loading: "Chargement des plats...",
    loadError: "Impossible de charger les plats.",
    noRestaurantError: "Aucun restaurant trouvé. Veuillez vous reconnecter.",
    missingTranslationsTitle: "Traductions manquantes",
    missingTranslationsSingle:
      "plat a des traductions manquantes. Modifiez-les pour ajouter toutes les langues requises.",
    missingTranslationsPlural:
      "plats ont des traductions manquantes. Modifiez-les pour ajouter toutes les langues requises.",
    colOrder: "Ordre",
    colIcon: "Icône",
    colEnglish: "Anglais",
    colFrench: "Français",
    colArabic: "Arabe",
    colDescription: "Description",
    colSizes: "Tailles",
    colAvailable: "Disponible",
    colStatus: "Statut",
    colLikes: "Likes",
    colActions: "Actions",
  },
} as const;
