export const generalText = {
  en: {
    error: "Unexpected error, please try again in few seconds.",
    errorTitle: "Unexpected error",
    imageUploadErrorTitle: "Image Upload Error",
    imageUploadMaxSizeExceededError: "The image must be smaller than 5 MB.",
    imageUploadUnsupportedFileTypeError: "Invalid file type. Please select an image.",
    reorderFailedTitle: "Reorder Failed",
    reorderFailed: "Reorder failed, please try again in few seconds.",
    savingErrorTitle: "Save Failed",
    savingError: "Save Failed, please try again in few seconds.",
    tryAgain: "Try Again",
    validationErrorTitle: "Validation Error",
    validationErrorMessage: "Please fix the highlighted fields.",
    uploadFailedTitle: "Upload Failed",
    uploadFailedMessage: "Upload Failed, please try again in few seconds.",
    deleteFailedTitle: "Delete Failed",
    deleteFailedMessage: "Delete Failed, please try again in few seconds.",
    updateFailedTitle: "Update Failed",
    updateFailedMessage: "Update Failed, please try again in few seconds."
  },
  fr: {
    error: "Une erreur inattendue s'est produite. Veuillez réessayer dans quelques secondes.",
    errorTitle: "Erreur inattendue",
    imageUploadErrorTitle: "Erreur de téléchargement",
    imageUploadMaxSizeExceededError: "La taille de l'image ne doit pas dépasser 5 Mo.",
    imageUploadUnsupportedFileTypeError: "Type de fichier invalide. Veuillez sélectionner une image.",
    reorderFailedTitle: "Échec du réordonnancement",
    reorderFailed: "Échec du réordonnancement. Veuillez réessayer dans quelques secondes.",
    savingErrorTitle: "Échec de l'enregistrement",
    savingError: "Échec de l'enregistrement. Veuillez réessayer dans quelques secondes.",
    tryAgain: "Réessayer",
    validationErrorTitle: "Erreur de validation",
    validationErrorMessage: "Veuillez corriger les champs en surbrillance.",
    uploadFailedTitle: "Échec du téléversement.",
    uploadFailedMessage: "Échec du téléversement. Veuillez réessayer dans quelques secondes.",
    deleteFailedTitle: "Échec de la suppression",
    deleteFailedMessage: "Échec de la suppression. Veuillez réessayer dans quelques secondes.",
    updateFailedTitle: "Échec de la mise à jour",
    updateFailedMessage: "Échec de la mise à jour. Veuillez réessayer dans quelques secondes."
  },
} as const;