export const loginText = {
  en: {
    appTitle: "Spectral QR",
    appSubtitle: "Restaurant Admin Dashboard",
    welcomeBack: "Welcome Back",
    emailLabel: "Email",
    emailPlaceholder: "your@email.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter your password",
    signIn: "Sign In",
    signingIn: "Signing in...",
    generalError: "Invalid email or password.",
    emailRequired: "Email is required.",
    emailInvalid: "Enter a valid email address.",
    passwordRequired: "Password is required.",
    passwordMinLength: "Password must be at least 6 characters.",
    copyright: "© 2024 Spectral QR. All rights reserved.",
  },
  fr: {
    appTitle: "Spectral QR",
    appSubtitle: "Tableau de bord administrateur",
    welcomeBack: "Bon retour",
    emailLabel: "E-mail",
    emailPlaceholder: "votre@email.com",
    passwordLabel: "Mot de passe",
    passwordPlaceholder: "Entrez votre mot de passe",
    signIn: "Se connecter",
    signingIn: "Connexion en cours...",
    generalError: "E-mail ou mot de passe invalide.",
    emailRequired: "L'e-mail est requis.",
    emailInvalid: "Entrez une adresse e-mail valide.",
    passwordRequired: "Le mot de passe est requis.",
    passwordMinLength: "Le mot de passe doit contenir au moins 6 caractères.",
    copyright: "© 2024 Spectral QR. Tous droits réservés.",
  },
} as const;