export const qrDisplayText = {
  en: {
    pageTitle: "QR Display",
    loading: "Loading QR display...",
    loadError: "Could not load QR information.",
    yourQrCodeTitle: "Your QR Code",
    yourQrCodeDescription:
      "Each menu has its own QR code. Guests scan it to open that specific menu.",
    defaultMenuBadge: "Default",
    noQrCode: "No QR code available. Please set a default menu first.",
    noPublicUrl: "No public menu URL configured yet.",
    publicMenuUrlTitle: "Public Menu URL",
    copyMenuUrl: "Copy Menu URL",
    downloadQr: "Download QR",
    testUrl: "Test URL",
    toastCopiedTitle: "Copied",
    toastCopiedMessage: "Public menu URL copied to clipboard.",
    toastCopyFailedTitle: "Copy Failed",
    toastCopyFailedMessage: "Could not copy the URL.",
    toastNoQrTitle: "No QR Code",
    toastNoQrMessage: "No QR code has been generated yet.",
    toastDownloadFailedTitle: "Download Failed",
    toastDownloadFailedMessage: "Could not find QR code canvas.",
    toastDownloadedTitle: "Downloaded",
    toastDownloadedMessage: "QR image download started.",
  },
  fr: {
    pageTitle: "Affichage QR",
    loading: "Chargement de l'affichage QR...",
    loadError: "Impossible de charger les informations du QR.",
    yourQrCodeTitle: "Votre code QR",
    yourQrCodeDescription:
      "Chaque menu possède son propre code QR. Les clients le scannent pour ouvrir ce menu.",
    defaultMenuBadge: "Par défaut",
    noQrCode:
      "Aucun code QR disponible. Veuillez d'abord définir un menu par défaut.",
    noPublicUrl: "Aucune URL de menu public configurée pour le moment.",
    publicMenuUrlTitle: "URL du menu public",
    copyMenuUrl: "Copier l'URL du menu",
    downloadQr: "Télécharger le QR",
    testUrl: "Tester l'URL",
    toastCopiedTitle: "Copié",
    toastCopiedMessage: "URL du menu public copiée dans le presse-papiers.",
    toastCopyFailedTitle: "Échec de la copie",
    toastCopyFailedMessage: "Impossible de copier l'URL.",
    toastNoQrTitle: "Aucun code QR",
    toastNoQrMessage: "Aucun code QR n'a encore été généré.",
    toastDownloadFailedTitle: "Échec du téléchargement",
    toastDownloadFailedMessage: "Impossible de trouver le canevas du code QR.",
    toastDownloadedTitle: "Téléchargé",
    toastDownloadedMessage: "Le téléchargement de l'image QR a commencé.",
  },
} as const;