export const supplementsText = {
  en: {
    pageTitle: "Supplement Manager",
    pageDescription: "Organize and manage your menu add-ons",
    addSupplement: "Add Supplement",
    loading: "Loading supplements...",
    noMenuError: "No restaurant or menu found. Please log in again.",
    missingTranslationsTitle: "Missing Translations",
    missingTranslationsSingle: "supplement has missing translations. Edit it to add all required languages.",
    missingTranslationsPlural: "supplements have missing translations. Edit them to add all required languages.",
    colEnglish: "English",
    colFrench: "Français",
    colArabic: "Arabic",
    colPrice: "Price",
    colAvailable: "Available",
    colStatus: "Status",
    colActions: "Actions",
  },
  fr: {
    pageTitle: "Gestionnaire de suppléments",
    pageDescription: "Organisez et gérez les suppléments de votre menu",
    addSupplement: "Ajouter un supplément",
    loading: "Chargement des suppléments...",
    noMenuError: "Aucun restaurant ou menu trouvé. Veuillez vous reconnecter.",
    missingTranslationsTitle: "Traductions manquantes",
    missingTranslationsSingle: "supplément a des traductions manquantes. Modifiez-le pour ajouter toutes les langues requises.",
    missingTranslationsPlural: "suppléments ont des traductions manquantes. Modifiez-les pour ajouter toutes les langues requises.",
    colEnglish: "Anglais",
    colFrench: "Français",
    colArabic: "Arabe",
    colPrice: "Prix",
    colAvailable: "Disponible",
    colStatus: "Statut",
    colActions: "Actions",
  },
} as const;