export const themePageText = {
  en: {
    pageTitle: "Menu Theme",
    pageDescription: "Choose how your public menu looks to customers.",
    loading: "Loading themes...",
    noThemesError: "No themes are available right now.",
    noMenuError: "No menu selected.",
    currentBadge: "Current",
    selectButton: "Select",
    selectedButton: "Selected",
    applying: "Applying...",
    toastSavedTitle: "Theme updated",
    toastSavedMessage: "Your menu now uses the new theme.",
    toastErrorTitle: "Could not update theme",
  },
  fr: {
    pageTitle: "Thème du menu",
    pageDescription: "Choisissez l'apparence de votre menu public.",
    loading: "Chargement des thèmes...",
    noThemesError: "Aucun thème n'est disponible pour le moment.",
    noMenuError: "Aucun menu sélectionné.",
    currentBadge: "Actuel",
    selectButton: "Choisir",
    selectedButton: "Sélectionné",
    applying: "Application...",
    toastSavedTitle: "Thème mis à jour",
    toastSavedMessage: "Votre menu utilise maintenant le nouveau thème.",
    toastErrorTitle: "Impossible de mettre à jour le thème",
  },
} as const;