export const sidebarText = {
  en: {
    overview: "Overview",
    categories: "Categories",
    dishes: "Dishes",
    supplements: "Supplements",
    menu: "Menu",
    banners: "Banners",
    qrDisplay: "QR Display",
    information: "Information",
    logout: "Log out",
    collapse: "Collapse sidebar",
    expand: "Expand sidebar",
  },
  fr: {
    overview: "Aperçu",
    categories: "Catégories",
    dishes: "Plats",
    supplements: "Suppléments",
    menu: "Menu",
    banners: "Bannières",
    qrDisplay: "Affichage QR",
    information: "Informations",
    logout: "Déconnexion",
    collapse: "Réduire le menu",
    expand: "Agrandir le menu",
  },
} as const;